# Generated by Django 5.2.8 on 2025-11-21 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پزشک')),
                ('specialty', models.CharField(max_length=100, verbose_name='تخصص')),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='عکس')),
                ('address', models.TextField(verbose_name='آدرس مطب')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('bio', models.TextField(verbose_name='بیوگرافی و توضیحات')),
                ('price', models.IntegerField(verbose_name='هزینه ویزیت (تومان)')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor')),
            ],
        ),
    ]
